// frontend-react/src/App.tsx
import { useEffect, useState } from 'react';
import { fetchConfig } from './config';
import reactLogo from './assets/react_icon.svg';
import { FaSun, FaMoon } from 'react-icons/fa';

type Item = { name: string; amount: number };

function App() {
  const [items, setItems] = useState<Item[]>([]);
  const [name, setName] = useState('');
  const [amount, setAmount] = useState<number>(1); 
  const [updateName, setUpdateName] = useState('');
  const [updateAmount, setUpdateAmount] = useState<number>(1);
  const [deleteName, setDeleteName] = useState('');
  const [defaultApiUrl, setDefaultApiUrl] = useState<string>('');
  const [customApiUrl, setCustomApiUrl] = useState<string>('');
  const [configError, setConfigError] = useState<string | null>(null);
  const [manualApiInput, setManualApiInput] = useState('');
  const [isDarkMode, setIsDarkMode] = useState(false);


  const getCurrentApiUrl = () => customApiUrl || defaultApiUrl;

  // Lädt API-URL aus Konfiguration
  const loadConfig = async () => {
    try {
      const config = await fetchConfig();
      setDefaultApiUrl(config.apiUrl);
      const stored = localStorage.getItem('apiUrl');
      
      if (stored) {
        setCustomApiUrl(stored);
      }
      
      setConfigError(null);
    } catch (err) {
      setConfigError('Fehler beim Laden der Konfiguration');
      console.error(err);
    }
  };

  // Ruft Items vom Server ab
  const loadItems = async (url: string) => {
    try {
      const res = await fetch(`${url}/items`);
      const data = await res.json();
      setItems(data);
      setConfigError(null);
    } catch (err) {
      setItems([]); // Liste leeren bei Fehler
      setConfigError('Fehler beim Laden der Items');
      console.error(err);
    }
  };

  // URL speichern und Daten neu laden
  const applyCustomUrl = async () => {
    localStorage.setItem('apiUrl', manualApiInput);
    setCustomApiUrl(manualApiInput);
    await loadItems(manualApiInput);
  };

  // Zurücksetzen auf Standard-URL
  const resetUrl = async () => {
    localStorage.removeItem('apiUrl');
    setCustomApiUrl(defaultApiUrl);
    setManualApiInput('');
    await loadItems(defaultApiUrl);
  };

  const addItem = async () => {
    try {
      await fetch(`${getCurrentApiUrl()}/items`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name, amount }),
      });
      setName('');
      setAmount(1);
      await loadItems(getCurrentApiUrl());
    } catch (err) {
      setConfigError('Fehler beim Hinzufügen des Items');
      console.error(err);
    }
  };

  const updateItem = async () => {
    try {
      await fetch(`${getCurrentApiUrl()}/items/${updateName}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ amount: updateAmount }),
      });
      setUpdateName('');
      setUpdateAmount(1);
      await loadItems(getCurrentApiUrl());
    } catch (err) {
      setConfigError('Fehler beim Aktualisieren des Items');
      console.error(err);
    }
  };

  const deleteItem = async () => {
    try {
      await fetch(`${getCurrentApiUrl()}/items/${deleteName}`, {
        method: 'DELETE',
      });
      setDeleteName('');
      await loadItems(getCurrentApiUrl());
    } catch (err) {
      setConfigError('Fehler beim Löschen des Items');
      console.error(err);
    }
  };

  const toggleDarkMode = () => {
    document.body.classList.toggle('dark');
    setIsDarkMode(!isDarkMode);
  };

  useEffect(() => {
    (async () => {
      await loadConfig();
      const url = localStorage.getItem('apiUrl') || defaultApiUrl;
      if (url) await loadItems(url);
    })();
  }, []);

  return (
    <>
      <header className="app-header">
        <span>Shopping List Manager</span>

        {/* Rechtsbündiges Logo */}
        <img src={reactLogo}
           alt="React logo"
           className="header-logo" />

        <button className="darkmode-toggle" onClick={toggleDarkMode}>
        {isDarkMode ? <FaSun className="icon-sun" /> : <FaMoon className="icon-moon" />}
        </button>
      </header>

      <div className="main-wrapper">
        <div className="container">
          {configError && <p className="error">{configError}</p>}

          <h3>All Shopping Items</h3>
          <table>
            <thead>
              <tr>
                <th>Item Name</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              {items.length === 0 ? (
                <tr>
                  <td colSpan={2} style={{ textAlign: 'center', opacity: 0.6 }}>
                    Keine Items geladen
                  </td>
                </tr>
              ) : (
                items.map(item => (
                  <tr key={item.name}>
                    <td>{item.name}</td>
                    <td>{item.amount}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>

          <h3>Add a New Item</h3>
          <form className="formx" onSubmit={e => e.preventDefault()}>
            <input type="text" value={name} onChange={e => setName(e.target.value)} placeholder="Name" required />
            <input type="number" value={amount} onChange={e => setAmount(+e.target.value)} placeholder="Amount" required />
            <button onClick={addItem} type="button">Add Item</button>
          </form>

          <h3>Update Item</h3>
          <form className="formx" onSubmit={e => e.preventDefault()}>
            <input type="text" value={updateName} onChange={e => setUpdateName(e.target.value)} placeholder="Name" required />
            <input type="number" value={updateAmount} onChange={e => setUpdateAmount(+e.target.value)} placeholder="Amount" required />
            <button onClick={updateItem} type="button">Update Item</button>
          </form>

          <h3>Delete Item</h3>
          <form className="formx" onSubmit={e => e.preventDefault()}>
            <input type="text" value={deleteName} onChange={e => setDeleteName(e.target.value)} placeholder="Name" required />
            <button onClick={deleteItem} type="button">Delete Item</button>
          </form>
        </div>

        <div className="right-wrapper">
        <div className="config-box">
          <h4>⚙️ Konfiguration</h4>

          <label htmlFor="api-url-input">Manuelle API-URL:</label>
          <input
  id="api-url-input"
  type="text"
  value={manualApiInput}
  onChange={e => setManualApiInput(e.target.value)}
  placeholder="https://example.com"
/>

          <button onClick={applyCustomUrl}>Anwenden</button>
          <button onClick={resetUrl}>🔄 Standard-Konfiguration laden</button>

          <p className="api-status">
            Aktive API: {getCurrentApiUrl() || 'nicht geladen'}{' '}
            {(!getCurrentApiUrl() || configError) && <span style={{ color: 'red' }}>⚠️</span>}
          </p>
        </div>
        <div className="info-box">
  <h4>🔌 Backend-Instanzen</h4>
  <ul>
    <li>
      <strong>Backend A:</strong> <code>Port 5000</code>
      <button
        className={`backend-switch ${getCurrentApiUrl().includes('5000') ? 'active' : ''}`}
        onClick={async () => {
          const hostname = window.location.hostname;
          const newUrl = `https://${hostname.replace('-6000', '-5000')}`;
          setCustomApiUrl(newUrl);
          localStorage.setItem('apiUrl', newUrl);
          await loadItems(newUrl);
        }}
      >
        {getCurrentApiUrl().includes('5000') ? 'Aktiv' : 'Verbinden mit Backend A'}
      </button>
    </li>
    <li>
      <strong>Backend B:</strong> <code>Port 5001</code>
      <button
        className={`backend-switch ${getCurrentApiUrl().includes('5001') ? 'active' : ''}`}
        onClick={async () => {
          const hostname = window.location.hostname;
          const newUrl = `https://${hostname.replace('-6000', '-5001')}`;
          setCustomApiUrl(newUrl);
          localStorage.setItem('apiUrl', newUrl);
          await loadItems(newUrl);
        }}
      >
        {getCurrentApiUrl().includes('5001') ? 'Aktiv' : 'Verbinden mit Backend B'}
      </button>
    </li>
  </ul>
</div>


        </div>
        
      </div>

     


      <footer>
        <p>&copy; Parallel Systems Study Project by Philipp Schlosser</p>
      </footer>
    </>
  );
}

export default App;

// frontend-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

type Item = {
  name: string;
  amount: number;
};

type Config = {
  apiUrl: string;
};

@Component({
  standalone: true,
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  imports: [CommonModule, FormsModule, HttpClientModule]
})
export class AppComponent implements OnInit {
  items: Item[] = [];

  name = '';
  amount = 1;
  updateName = '';
  updateAmount = 1;
  deleteName = '';

  defaultApiUrl = '';
  customApiUrl = '';
  manualApiInput = '';
  configError: string | null = null;

  constructor(private http: HttpClient) {}

  getCurrentApiUrl(): string {
    return this.customApiUrl || this.defaultApiUrl;
  }

  isDarkMode = false;

  toggleDarkMode() {
    this.isDarkMode = !this.isDarkMode;
    document.body.classList.toggle('dark', this.isDarkMode);
  }

  async ngOnInit() {
    const defaultUrl = await this.loadConfig();
    const stored = localStorage.getItem('apiUrl');
    const url = stored ?? defaultUrl ?? '';

    this.customApiUrl = url;
    this.manualApiInput = '';
    await this.loadItems(url);
  }

  async loadConfig(): Promise<string> {
    try {
      const config = await this.http.get<Config>('assets/config.json').toPromise();
      let apiUrl = config?.apiUrl?.trim();

      if (!apiUrl) {
        const host = window.location.hostname;
        apiUrl = `https://${host.replace('-6001', '-5001')}`;
      }

      this.defaultApiUrl = apiUrl;
      this.configError = null;
      return apiUrl;
    } catch (err) {
      this.configError = 'Fehler beim Laden der Konfiguration';
      console.error(err);
      return '';
    }
  }

  async loadItems(url: string) {
    try {
      const items = await this.http.get<Item[]>(`${url}/items`).toPromise();
      this.items = items ?? [];
      this.configError = null;
    } catch (err) {
      this.items = [];
      this.configError = 'Fehler beim Laden der Items';
      console.error(err);
    }
  }

  async applyCustomUrl() {
    if (!this.manualApiInput.trim()) return;
    localStorage.setItem('apiUrl', this.manualApiInput);
    this.customApiUrl = this.manualApiInput;
    await this.loadItems(this.manualApiInput);
  }

  async resetUrl() {
    localStorage.removeItem('apiUrl');
    this.customApiUrl = this.defaultApiUrl;
    this.manualApiInput = '';
    await this.loadItems(this.defaultApiUrl);
  }

  async switchToBackend(port: string) {
    const host = window.location.hostname;
    const targetUrl = `https://${host.replace('-6001', `-${port}`)}`;
    localStorage.setItem('apiUrl', targetUrl);
    this.customApiUrl = targetUrl;
    this.manualApiInput = '';
    await this.loadItems(targetUrl);
  }

  async addItem() {
    try {
      await this.http.post(`${this.getCurrentApiUrl()}/items`, {
        name: this.name,
        amount: this.amount,
      }).toPromise();
      this.name = '';
      this.amount = 1;
      await this.loadItems(this.getCurrentApiUrl());
    } catch (err) {
      this.configError = 'Fehler beim Hinzufügen des Items';
      console.error(err);
    }
  }

  async updateItem() {
    try {
      await this.http.put(`${this.getCurrentApiUrl()}/items/${this.updateName}`, {
        amount: this.updateAmount,
      }).toPromise();
      this.updateName = '';
      this.updateAmount = 1;
      await this.loadItems(this.getCurrentApiUrl());
    } catch (err) {
      this.configError = 'Fehler beim Aktualisieren des Items';
      console.error(err);
    }
  }

  async deleteItem() {
    try {
      await this.http.delete(`${this.getCurrentApiUrl()}/items/${this.deleteName}`).toPromise();
      this.deleteName = '';
      await this.loadItems(this.getCurrentApiUrl());
    } catch (err) {
      this.configError = 'Fehler beim Löschen des Items';
      console.error(err);
    }
  }
}

<header class="app-header">
  <span>Shopping List Manager</span>
  <img src="assets/angular_icon.svg" alt="Angular logo" class="header-logo" />

  <button class="darkmode-toggle" (click)="toggleDarkMode()">
    <img
      [src]="isDarkMode ? 'assets/sun.svg' : 'assets/moon.svg'"
      alt="Toggle dark mode"
      width="25"
      height="25"
      class="icon"
    />
  </button>
</header>

<div class="main-wrapper">
  <div class="container">
    <p *ngIf="configError" class="error">{{ configError }}</p>

    <h3>All Shopping Items</h3>
    <table>
      <thead>
        <tr>
          <th>Item Name</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngIf="items.length === 0">
          <td colspan="2" style="text-align: center; opacity: 0.6">
            Keine Items geladen
          </td>
        </tr>
        <tr *ngFor="let item of items">
          <td>{{ item.name }}</td>
          <td>{{ item.amount }}</td>
        </tr>
      </tbody>
    </table>

    <h3>Add a New Item</h3>
    <form class="formx" (submit)="addItem(); $event.preventDefault()">
      <input type="text" [(ngModel)]="name" name="name" placeholder="Name" required />
      <input
        type="number"
        [(ngModel)]="amount"
        name="amount"
        placeholder="Amount"
        required
      />
      <button type="submit">Add Item</button>
    </form>

    <h3>Update Item</h3>
    <form class="formx" (submit)="updateItem(); $event.preventDefault()">
      <input
        type="text"
        [(ngModel)]="updateName"
        name="updateName"
        placeholder="Name"
        required
      />
      <input
        type="number"
        [(ngModel)]="updateAmount"
        name="updateAmount"
        placeholder="Amount"
        required
      />
      <button type="submit">Update Item</button>
    </form>

    <h3>Delete Item</h3>
    <form class="formx" (submit)="deleteItem(); $event.preventDefault()">
      <input
        type="text"
        [(ngModel)]="deleteName"
        name="deleteName"
        placeholder="Name"
        required
      />
      <button type="submit">Delete Item</button>
    </form>
  </div>

  <div class="right-wrapper">
    <div class="config-box">
      <h4>⚙️ Konfiguration</h4>

      <label for="api-url-input">Manuelle API-URL:</label>
      <input
        id="api-url-input"
        type="text"
        [(ngModel)]="manualApiInput"
        name="api"
        placeholder="https://example.com"
      />

      <button (click)="applyCustomUrl()">Anwenden</button>
      <button (click)="resetUrl()">🔄 Standard-Konfiguration laden</button>

      <p class="api-status">
        Aktive API: {{ getCurrentApiUrl() || 'nicht geladen' }}
        <span *ngIf="!getCurrentApiUrl() || configError" style="color: red">⚠️</span>
      </p>
    </div>

    <div class="info-box">
      <h4>🔌 Backend-Instanzen</h4>
      <ul>
        <li>
          <strong>Backend A:</strong> <code>Port 5000</code>
          <button
            class="backend-switch"
            [ngClass]="{ 'active': getCurrentApiUrl().includes('5000') }"
            (click)="switchToBackend('5000')"
          >
            {{
              getCurrentApiUrl().includes('5000')
                ? 'Aktiv'
                : 'Verbinden mit Backend A'
            }}
          </button>
        </li>
        <li>
          <strong>Backend B:</strong> <code>Port 5001</code>
          <button
            class="backend-switch"
            [ngClass]="{ 'active': getCurrentApiUrl().includes('5001') }"
            (click)="switchToBackend('5001')"
          >
            {{
              getCurrentApiUrl().includes('5001')
                ? 'Aktiv'
                : 'Verbinden mit Backend B'
            }}
          </button>
        </li>
      </ul>
    </div>
  </div>
</div>

<footer>
  <p>&copy; Parallel Systems Study Project by Philipp Schlosser</p>
</footer>
